---
title: "time"
format: html
editor: visual
---

## [Access the slides, code, and other materials at the course website](https://datavizm20.classes.andrewheiss.com/content/11-content/)

## [Slides](https://datavizm20.classes.andrewheiss.com/content/11-content/#slides)

## [Download the data and see the polished code](https://datavizm20.classes.andrewheiss.com/example/11-example/)

## [Youtube playlist](https://www.youtube.com/watch?v=yuBMJF0ncyI&list=PLS6tnpTr39sG0DXT1Bvx0-hQkHrWBABa1&index=2)

```{r}

#| warning = FALSE
#| message = FALSE
library(tidyverse) # for ggplot, dylyr and friends
library(tidyquant) # for accessing fred data
library(scales) # for nicer labels
```

```{r}
  fred_raw <- tq_get(c("RSXFSN",  # Advance retail sales
                     "GDPC1",  # GDP
                     "ICSA",  # Initial unemployment claims
                     "FPCPITOTLZGUSA",  # Inflation
                     "UNRATE",  # Unemployment rate
                     "USREC"),  # Recessions
                   get = "economic.data",  # Use FRED
                   from = "1990-01-01")
fred_raw 
```

```{r}
retail_sales <- fred_raw |> 
  filter(symbol == "RSXFSN")

ggplot(data = retail_sales, 
       mapping = aes(x = date, y = price)) + 
  geom_line()
```

```{r}
unempoly_claims <- fred_raw |> 
  filter(symbol == "ICSA")

ggplot(data = unempoly_claims, 
       mapping = aes(x = date, 
       y = price)) + 
  geom_line()
```

```{r}
recessions_raw <- fred_raw |> 
  filter(symbol == "USREC")
# we wanted to see the recession perios start and end of recessions

recessions_start_end <- recessions_raw |>
  mutate(recession_change = price - lag(price)) |> 
  filter(recession_change != 0)


recessions <- tibble(
  start = recessions_start_end |> filter(recession_change == 1) |> pull(date), 
  end = recessions_start_end |> filter(recession_change == -1) |> pull(date)
)
```

## Lets look at the GDP data

```{r}
gdp <- fred_raw |> 
  filter(symbol == "GDPC1") 

ggplot() +
  geom_rect(data= recessions,
            aes(
            xmin = start, 
            xmax = end, 
            ymin = -Inf, 
            ymax = Inf)) +
  geom_line(data= gdp, aes(x = date, y = price))

# better way if we want to keep the global data and aes labels under global options to be used later

ggplot(data= gdp, aes(x = date, y = price)) +
  geom_rect(data= recessions,
            aes(
            xmin = start, 
            xmax = end, 
            ymin = -Inf, 
            ymax = Inf), 
            fill = 'yellow', 
            alpha = 0.5, 
            inherit.aes = FALSE) +
  geom_line()
  
```

## for the decomposition of trend and seasonilty pls visit the code link above. 
